DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE messages(
  id SERIAL PRIMARY KEY,
  text VARCHAR(255),
  user_id INT NOT NULL REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);